#
# Default values for helm3-template.
# https://helm.sh/docs/topics/chart_best_practices/values/#document-values-yaml
#

# Function and image name in deployment manifest
app: template

# Amount of Pods to be spinned-up
replicaCount: 1

# Registry from which images will be pulled on deployment
registry: harbor.rickyvanrijn.nl

# Path in the registry from which the image will be pulled
project: wiremock-service

#Database properties
database_user: postgres
database_password: root

# Image version
appVersion: "latest"

# Using Never for local testing purposes
imagePullPolicy: Always

# Registry credentials; is ignored when imagePullPolicy=Never
imagePuller: harbor-puller

# Rules for incoming network traffic
ingress:
  # DNS
  url: wiremock-service.rickyvanrijn.nl
  tls:
    # Defines server-certificate
    secret: wildcard-tls # Using default self-signed certificate by Kubernetes Ingress Controller/Nginx